[default]
src = 'contracts'
test = 'test'
out = 'artifacts'
libs = ['node_modules']
remappings = [
    '@ensdomains/=node_modules/@ensdomains/',
    '@openzeppelin/=node_modules/@openzeppelin/',
    'eth-gas-reporter/=node_modules/eth-gas-reporter/',
    'hardhat/=node_modules/hardhat/',
    'ds-test/=lib/ds-test/src/',
]

# See more config options https://github.com/gakonst/foundry/tree/master/config