on: [push]

name: test

jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/setup-node@v2

      - name: Install dependencies
        run: yarn install
      
      - name: Install frontend dependencies
        run: cd ./app/nft-social-recovery && yarn install

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly
      
      - name: Run linter
        run: yarn lint

      - name: Run forge tests
        run: forge test -vvv
      
      - name: Run hardhat tests
        run: yarn hardhat test
      
      - name: Run frontend tests
        run: cd ./app/nft-social-recovery && yarn test